- uses: jodersky/setup-mill@master
  with:
    mill-version: 0.10.10
- name: JVMDesktop
  run: mill lambdaDesktopJVM.run
# the server process is kept alive across steps,
# so separate invocations of mill remain extremely fast!
- name: Test
  run: mill lambdaCoreJVM.tests